In [1]:
from setting import get_engine
import pandas as pd

In [2]:
engine = get_engine('db_stock','local')

In [3]:
df = pd.read_sql('tb_bond_jisilu',con=engine)

C:\ProgramData\Anaconda3\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect string value: '\\xD6\\xD0\\xB9\\xFA\\xB1\\xEA...' for column 'VARIABLE_VALUE' at row 480")
  result = self._query(query)

In [5]:
df.head()

    可转债代码 可转债名称   可转债价格  正股名称    正股代码   正股现价        ...         下调次数  转债剩余占总市值比   剩余规模   发行规模  股东配售率              更新日期
0  127008  特发转债  185.60  特发信息  000070  16.29        ...            0        4.1  4.194  4.194  45.92  2019-03-13 15:31
1  110050  佳都转债  135.49  佳都科技  600728  11.90        ...            0        4.5  8.747  8.747  14.08  2019-03-13 15:31
2  128053  尚荣转债  119.50  尚荣医疗  002551   6.41        ...            0       16.6  7.500  7.500  15.80  2019-03-13 15:31
3  123018  溢利转债  114.45   溢多利  300381  10.27        ...            0       15.9  6.650  6.650  35.63  2019-03-13 15:31
4  123016  洲明转债  135.64  洲明科技  300232  13.63        ...            0        5.3  5.480  5.480  33.98  2019-03-13 15:31

[5 rows x 29 columns]

In [4]:
zg_list = list(df['正股代码'].values)

In [7]:
zg_list

['000070',
 '600728',
 '002551',
 '300381',
 '300232',
 '603305',
 '002783',
 '000811',
 '603313',
 '603626',
 '002131',
 '603668',
 '600567',
 '601311',
 '300601',
 '300057',
 '300058',
 '002446',
 '300409',
 '600372',
 '601128',
 '300059',
 '603228',
 '002548',
 '002224',
 '000665',
 '603323',
 '300297',
 '600031',
 '300197',
 '300539',
 '600831',
 '603421',
 '603797',
 '600233',
 '002839',
 '002787',
 '002807',
 '603518',
 '300388',
 '300473',
 '601727',
 '603677',
 '002793',
 '603569',
 '601012',
 '603568',
 '603588',
 '603023',
 '300568',
 '002815',
 '002100',
 '603055',
 '002142',
 '601929',
 '601127',
 '600483',
 '002728',
 '002658',
 '300407',
 '002865',
 '600690',
 '603816',
 '000001',
 '601233',
 '603019',
 '002758',
 '603345',
 '600908',
 '300618',
 '601818',
 '002179',
 '603989',
 '600863',
 '002318',
 '600755',
 '002823',
 '002562',
 '603179',
 '000783',
 '002741',
 '600183',
 '601211',
 '603618',
 '002013',
 '603738',
 '000861',
 '601966',
 '603225',
 '000623',
 '600998',
 '300422',
 '600566',
 '002273',
 '002258',
 '002717',
 '603601',
 '002271',
 '002753',
 '603027',
 '002078',
 '600398',
 '002542',
 '601238',
 '002472',
 '002597',
 '002008',
 '002772',
 '600185',
 '002279',
 '603822',
 '601222',
 '002460',
 '002707',
 '002284',
 '002527',
 '600271',
 '002245',
 '300433',
 '000700',
 '002325',
 '002496']

In [5]:
import tushare as ts

In [6]:
basic_df = ts.get_stock_basics()

In [7]:
basic_df.head()

,name,industry,area,pe,outstanding,totals,totalAssets,liquidAssets,fixedAssets,reserved,...,bvps,pb,timeToMarket,undp,perundp,rev,profit,gpr,npr,holders
code,,,,,,,,,,,,,,,,,,,,,
300116,坚瑞沃能,电气设备,陕西,0.00,12.94,24.33,1566351.50,1150821.75,238616.80,490198.44,...,-0.14,-14.68,20100902,-766017.63,-3.15,-90.40,-69.27,24.37,-503.89,68130.0
000677,恒天海龙,化纤,山东,1010.84,8.64,8.64,88712.68,34382.80,45130.65,69768.81,...,0.32,13.34,19961226,-149955.27,-1.74,32.77,287.29,15.19,0.45,77347.0
300152,科融环境,环境保护,江苏,9.27,7.13,7.13,195568.00,99731.43,19260.75,50605.01,...,1.11,4.12,20101229,-47372.92,-0.66,0.43,686.96,19.61,113.39,61878.0
001896,豫能控股,火力发电,河南,25.91,9.30,11.51,2086533.63,445571.75,1194374.75,500207.81,...,4.99,0.81,19980122,-58811.98,-0.51,-21.34,122.22,9.47,2.36,34008.0
600095,哈高科,区域地产,黑龙江,0.00,3.61,3.61,106868.85,37246.34,17327.35,26740.84,...,2.32,2.35,19970708,17464.70,0.48,189.72,-44.87,17.66,-7.98,44532.0

In [8]:
basic_df_reset = basic_df.reset_index()

In [9]:
basic_df_reset.head()

,code,name,industry,area,pe,outstanding,totals,totalAssets,liquidAssets,fixedAssets,...,bvps,pb,timeToMarket,undp,perundp,rev,profit,gpr,npr,holders
0,300116,坚瑞沃能,电气设备,陕西,0.00,12.94,24.33,1566351.50,1150821.75,238616.80,...,-0.14,-14.68,20100902,-766017.63,-3.15,-90.40,-69.27,24.37,-503.89,68130.0
1,000677,恒天海龙,化纤,山东,1010.84,8.64,8.64,88712.68,34382.80,45130.65,...,0.32,13.34,19961226,-149955.27,-1.74,32.77,287.29,15.19,0.45,77347.0
2,300152,科融环境,环境保护,江苏,9.27,7.13,7.13,195568.00,99731.43,19260.75,...,1.11,4.12,20101229,-47372.92,-0.66,0.43,686.96,19.61,113.39,61878.0
3,001896,豫能控股,火力发电,河南,25.91,9.30,11.51,2086533.63,445571.75,1194374.75,...,4.99,0.81,19980122,-58811.98,-0.51,-21.34,122.22,9.47,2.36,34008.0
4,600095,哈高科,区域地产,黑龙江,0.00,3.61,3.61,106868.85,37246.34,17327.35,...,2.32,2.35,19970708,17464.70,0.48,189.72,-44.87,17.66,-7.98,44532.0

In [10]:
zg_df = basic_df_reset[basic_df_reset['code'].isin(zg_list)]

In [11]:
zg_df.head()

,code,name,industry,area,pe,outstanding,totals,totalAssets,liquidAssets,fixedAssets,...,bvps,pb,timeToMarket,undp,perundp,rev,profit,gpr,npr,holders
39,002370,亚太药业,化学制药,浙江,42.56,4.08,5.36,358351.47,139768.77,39471.57,...,4.79,3.76,20100316,66509.30,1.24,14.71,-13.28,38.51,15.51,13554.0
43,002865,钧达股份,汽车配件,海南,0.00,0.38,1.22,188553.88,101527.11,37024.60,...,6.86,3.10,20170425,31624.21,2.60,-46.04,-324.05,11.07,-21.88,15562.0
152,002823,凯中精密,机械基件,深圳,44.71,1.00,2.91,290706.91,110901.63,122522.60,...,4.22,2.72,20161124,51572.82,1.77,36.55,-49.13,22.75,3.86,17767.0
203,603517,绝味食品,食品,湖南,26.35,1.64,4.10,497797.69,255355.80,104238.86,...,8.08,5.77,20170317,189023.77,4.61,19.63,20.38,33.31,15.71,7829.0
206,603668,天马科技,饲料,福建,51.59,2.03,3.17,217281.22,156485.25,41197.48,...,3.14,2.94,20170117,34508.59,1.09,16.41,-18.26,15.71,4.00,21640.0

In [12]:
len(zg_df)

156

In [13]:
zg_df['outstanding'].mean()

16.904038461538462

In [14]:
zg_df['outstanding'].min()

0.38

In [15]:
zg_df['outstanding'].idxmin()

43

In [16]:
zg_df.loc[43]

code                  002865
name                    钧达股份
industry                汽车配件
area                      海南
pe                         0
outstanding             0.38
totals                  1.22
totalAssets           188554
liquidAssets          101527
fixedAssets          37024.6
reserved             38567.8
reservedPerShare        3.17
esp                   -0.266
bvps                    6.86
pb                       3.1
timeToMarket        20170425
undp                 31624.2
perundp                  2.6
rev                   -46.04
profit               -324.05
gpr                    11.07
npr                   -21.88
holders                15562
Name: 43, dtype: object

In [17]:
engine_daily = get_engine('db_daily')
price_df = pd.read_sql('2019-05-07',con=engine_daily)

C:\ProgramData\Anaconda3\lib\site-packages\pymysql\cursors.py:170: Warning: (1366, "Incorrect string value: '\\xD6\\xD0\\xB9\\xFA\\xB1\\xEA...' for column 'VARIABLE_VALUE' at row 480")
  result = self._query(query)

In [18]:
price_df.head()

,index,code,name,changepercent,trade,open,high,low,settlement,volume,turnoverratio,amount,per,pb,mktcap,nmc
0,0,603999,读者传媒,1.460,5.56,5.53,5.58,5.43,5.48,3359170.0,0.58,18514861.0,79.43,1.90,3.202560e+05,3.202560e+05
1,1,603998,方盛制药,8.407,9.80,9.22,9.94,9.20,9.04,43037343.0,10.12,415992580.0,57.65,3.97,4.278903e+05,4.166928e+05
2,2,603997,继峰股份,3.193,9.05,8.85,9.20,8.82,8.77,3838299.0,0.61,34615531.0,18.98,2.99,5.786689e+05,5.701500e+05
3,3,603996,中新科技,2.782,7.39,7.22,7.47,7.21,7.19,6499731.0,2.17,47818285.0,-28.42,1.64,2.218109e+05,2.218109e+05
4,4,603993,洛阳钼业,1.535,3.97,3.95,4.01,3.90,3.91,77051549.0,0.44,305448553.0,18.46,2.10,8.574899e+06,7.013312e+06

In [19]:
price_df[price_df['code'].isin(zg_list)][['code','trade']]

        code  trade
7     603989  18.13
51    603897  20.54
60    603883  60.29
67    603876  15.84
88    603822  24.92
91    603817   6.86
92    603816  46.78
104   603797  13.28
120   603738  12.89
158   603677  13.21
161   603668   9.26
183   603626   8.65
185   603618   5.99
198   603601   8.99
206   603588  10.16
215   603569  11.55
216   603568  24.38
232   603518  13.50
233   603517  46.59
282   603345  45.58
295   603323   6.85
304   603313  23.31
309   603305  24.35
330   603233  48.60
336   603225  13.00
358   603179  14.78
404   603081  12.45
419   603055  10.24
437   603027  23.16
440   603023   5.38
...      ...    ...
2709  002439  24.67
2757  002391  13.54
2778  002370  18.02
2823  002325   3.33
2830  002318   7.03
2864  002284   4.96
2869  002279   7.04
2875  002273  12.28
2877  002271  19.88
2890  002258  15.11
2902  002245   4.54
2923  002224   6.23
2968  002179  41.40
3005  002142  22.16
3008  002139   5.96
3016  002131   2.07
3047  002100   9.18
3069  002078   6.56
3134  002013   7.14
3139  002008  38.31
3148  001965   8.10
3237  000887  10.38
3252  000861   2.58
3283  000811   8.23
3305  000783   7.49
3360  000700   3.71
3388  000665   8.05
3413  000623  17.04
3556  000070  13.40
3609  000001  12.95

[156 rows x 2 columns]

In [ ]:
# liutong 实时的流通市值

In [20]:
for i in zg_df.index:
    p=price_df[price_df['code']==zg_df.loc[i]['code']]['trade'].values[0]
    ltgb=zg_df.loc[i]['outstanding']
    t=p*ltgb
    zg_df.loc[i,'liutong']=t

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:362: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[key] = _infer_fill_value(value)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [44]:
zg_df['liutong']=0

c:\python3_64\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [43]:
zg_df.loc[1175,'price']

0

In [21]:
zg_df.head()

,code,name,industry,area,pe,outstanding,totals,totalAssets,liquidAssets,fixedAssets,...,pb,timeToMarket,undp,perundp,rev,profit,gpr,npr,holders,liutong
39,002370,亚太药业,化学制药,浙江,42.56,4.08,5.36,358351.47,139768.77,39471.57,...,3.76,20100316,66509.30,1.24,14.71,-13.28,38.51,15.51,13554.0,73.5216
43,002865,钧达股份,汽车配件,海南,0.00,0.38,1.22,188553.88,101527.11,37024.60,...,3.10,20170425,31624.21,2.60,-46.04,-324.05,11.07,-21.88,15562.0,8.0636
152,002823,凯中精密,机械基件,深圳,44.71,1.00,2.91,290706.91,110901.63,122522.60,...,2.72,20161124,51572.82,1.77,36.55,-49.13,22.75,3.86,17767.0,11.4700
203,603517,绝味食品,食品,湖南,26.35,1.64,4.10,497797.69,255355.80,104238.86,...,5.77,20170317,189023.77,4.61,19.63,20.38,33.31,15.71,7829.0,76.4076
206,603668,天马科技,饲料,福建,51.59,2.03,3.17,217281.22,156485.25,41197.48,...,2.94,20170117,34508.59,1.09,16.41,-18.26,15.71,4.00,21640.0,18.7978

In [22]:
del zg_df['price']

KeyError: 'price'

In [23]:
final_df = zg_df.reset_index(drop=True)

In [24]:
final_df.head()

,code,name,industry,area,pe,outstanding,totals,totalAssets,liquidAssets,fixedAssets,...,pb,timeToMarket,undp,perundp,rev,profit,gpr,npr,holders,liutong
0,002370,亚太药业,化学制药,浙江,42.56,4.08,5.36,358351.47,139768.77,39471.57,...,3.76,20100316,66509.30,1.24,14.71,-13.28,38.51,15.51,13554.0,73.5216
1,002865,钧达股份,汽车配件,海南,0.00,0.38,1.22,188553.88,101527.11,37024.60,...,3.10,20170425,31624.21,2.60,-46.04,-324.05,11.07,-21.88,15562.0,8.0636
2,002823,凯中精密,机械基件,深圳,44.71,1.00,2.91,290706.91,110901.63,122522.60,...,2.72,20161124,51572.82,1.77,36.55,-49.13,22.75,3.86,17767.0,11.4700
3,603517,绝味食品,食品,湖南,26.35,1.64,4.10,497797.69,255355.80,104238.86,...,5.77,20170317,189023.77,4.61,19.63,20.38,33.31,15.71,7829.0,76.4076
4,603668,天马科技,饲料,福建,51.59,2.03,3.17,217281.22,156485.25,41197.48,...,2.94,20170117,34508.59,1.09,16.41,-18.26,15.71,4.00,21640.0,18.7978

In [25]:
final_df.to_sql('tb_zhenggu_liutong_2019-05-07',engine)